name: do-frappe
services:
- name: frappe
  source_dir: .
  github:
    branch: main
    deploy_on_push: true
    repo: willmatic/do-frappe
  dockerfile_path: images/frappe/Dockerfile
  http_port: 8000
  instance_count: 1
  instance_size_slug: basic-xxs
  internal_ports:
  - 8000
  - 8080
  - 8888
  - 9000
  routes:
  - path: /
  envs:
  - key: REDIS_CACHE
    scope: RUN_AND_BUILD_TIME
    value: "redis://redis-cache:6379"
  - key: REDIS_QUEUE
    scope: RUN_AND_BUILD_TIME
    value: "redis://redis-queue:6379"
  - key: REDIS_SOCKETIO
    scope: RUN_AND_BUILD_TIME
    value: "redis://redis-socketio:6379"
  - key: DB_HOST
    scope: RUN_AND_BUILD_TIME
    value: "mariadb"
  - key: DB_PORT
    scope: RUN_AND_BUILD_TIME
    value: "3306"

- name: mariadb
  source_dir: .
  github:
    branch: main
    deploy_on_push: true
    repo: willmatic/do-frappe
  dockerfile_path: images/mariadb/Dockerfile
  instance_count: 1
  instance_size_slug: basic-xxs
  internal_ports:
  - 3306
  envs:
  - key: MARIADB_ROOT_PASSWORD
    scope: RUN_AND_BUILD_TIME
    value: "pEBMMlB1s2H6oBQE07Bw4phoQhnlqSGa"

- name: redis-cache
  source_dir: .
  github:
    branch: main
    deploy_on_push: true
    repo: willmatic/do-frappe
  dockerfile_path: images/redis/Dockerfile
  instance_count: 1
  instance_size_slug: basic-xxs
  internal_ports:
  - 6379

- name: redis-queue
  source_dir: .
  github:
    branch: main
    deploy_on_push: true
    repo: willmatic/do-frappe
  dockerfile_path: images/redis/Dockerfile
  instance_count: 1
  instance_size_slug: basic-xxs
  internal_ports:
  - 6379

- name: redis-socketio
  source_dir: .
  github:
    branch: main
    deploy_on_push: true
    repo: willmatic/do-frappe
  dockerfile_path: images/redis/Dockerfile
  instance_count: 1
  instance_size_slug: basic-xxs
  internal_ports:
  - 6379
